[00:07:50:512] [main/INFO]: Start GameLogicHandler
[00:07:50:615] [main/INFO]: Load mobs
[00:07:51:112] [main/INFO]: Load stores
[00:07:51:191] [main/INFO]: Load locations
[00:07:51:201] [main/INFO]: Start NetworkSystem
[00:07:55:171] [nioEventLoopGroup-0-1/INFO]: Соединение установлено
[00:07:55:211] [nioEventLoopGroup-0-1/INFO]: Decoder HANDSHAKING, packet CHandshake, id 0, size 3
[00:07:55:211] [nioEventLoopGroup-0-1/INFO]: Connect Battle server
[00:08:01:977] [nioEventLoopGroup-0-2/INFO]: Соединение установлено
[00:08:01:994] [nioEventLoopGroup-0-2/INFO]: Decoder HANDSHAKING, packet CHandshake, id 0, size 3
[00:08:01:994] [nioEventLoopGroup-0-2/INFO]: Decoder LOGIN, packet CPacketLoginStart, id 0, size 22
[00:08:02:000] [pool-2-thread-10/INFO]: Start initialize player id=1
[00:08:02:003] [nioEventLoopGroup-0-2/INFO]: Encoder LOGIN, packet SPacketLoginSuccess, id 1, size 2
[00:08:02:005] [pool-2-thread-10/INFO]: Load player id=1
[00:08:02:034] [pool-2-thread-10/INFO]: End initialize player id=1 name=Test_1
[00:08:02:035] [nioEventLoopGroup-0-2/INFO]: Encoder PLAY, packet SPacketPlayerInfo, id 1, size 34
[00:08:02:036] [nioEventLoopGroup-0-2/INFO]: Encoder PLAY, packet SPacketInventory, id 3, size 111
[00:08:02:039] [nioEventLoopGroup-0-2/INFO]: Encoder PLAY, packet SPacketBody, id 4, size 110
[00:08:02:042] [nioEventLoopGroup-0-2/INFO]: Encoder PLAY, packet SPacketSlots, id 9, size 10
[00:08:02:043] [nioEventLoopGroup-0-2/INFO]: Encoder PLAY, packet SPacketLocInfo, id 2, size 200
[00:08:02:044] [nioEventLoopGroup-0-2/INFO]: Encoder PLAY, packet SPacketPlayerLocation, id 8, size 10
[00:08:02:044] [nioEventLoopGroup-0-2/INFO]: Encoder PLAY, packet SPacketPlayerLocation, id 8, size 26
[00:08:04:414] [nioEventLoopGroup-0-2/INFO]: Decoder PLAY, packet CPacketAction, id 0, size 15
[00:08:04:416] [nioEventLoopGroup-0-1/INFO]: Encoder BATTLE_SERVER, packet PCreateBattle, id 0, size 16
[00:08:04:447] [nioEventLoopGroup-0-1/INFO]: Decoder BATTLE_SERVER, packet PBattleStatus, id 0, size 7
[00:08:04:449] [nioEventLoopGroup-0-2/INFO]: Encoder PLAY, packet SPacketStartBattle, id 7, size 6
[00:09:22:035] [nioEventLoopGroup-0-1/INFO]: exceptionCaught
java.io.IOException: Удаленный хост принудительно разорвал существующее подключение
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_151]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_151]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_151]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:311) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:853) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:240) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:115) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:514) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:471) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:385) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:351) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
[00:09:22:041] [nioEventLoopGroup-0-1/INFO]: [Battle Server, exceptionCaught] lost connection: {}
[00:09:22:041] [nioEventLoopGroup-0-1/INFO]: Соединение разорвано
[00:09:26:585] [nioEventLoopGroup-0-4/INFO]: Соединение установлено
[00:09:26:628] [nioEventLoopGroup-0-4/INFO]: Decoder HANDSHAKING, packet CHandshake, id 0, size 3
[00:09:26:629] [nioEventLoopGroup-0-4/INFO]: Connect Battle server
[00:09:29:671] [nioEventLoopGroup-0-2/INFO]: Decoder PLAY, packet CPacketAction, id 0, size 15
[00:09:29:673] [nioEventLoopGroup-0-4/INFO]: Encoder BATTLE_SERVER, packet PCreateBattle, id 0, size 16
[00:09:44:382] [nioEventLoopGroup-0-3/INFO]: Decoder BATTLE_SERVER, packet PBattleStatus, id 0, size 7
[00:09:44:384] [nioEventLoopGroup-0-2/INFO]: Encoder PLAY, packet SPacketStartBattle, id 7, size 6
[00:10:14:613] [nioEventLoopGroup-0-2/INFO]: Decoder PLAY, packet CPacketAction, id 0, size 15
[00:10:14:614] [nioEventLoopGroup-0-3/INFO]: Encoder BATTLE_SERVER, packet PCreateBattle, id 0, size 16
[00:10:17:227] [nioEventLoopGroup-0-2/INFO]: Decoder PLAY, packet CPacketAction, id 0, size 15
[00:10:17:228] [nioEventLoopGroup-0-3/INFO]: Encoder BATTLE_SERVER, packet PCreateBattle, id 0, size 16
[00:10:26:004] [nioEventLoopGroup-0-0/INFO]: exceptionCaught
java.io.IOException: Удаленный хост принудительно разорвал существующее подключение
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_151]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_151]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_151]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:311) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:853) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:240) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:115) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:514) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:471) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:385) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:351) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
[00:10:26:006] [nioEventLoopGroup-0-0/INFO]: [Battle Server, exceptionCaught] lost connection: {}
[00:10:26:007] [nioEventLoopGroup-0-0/INFO]: Соединение разорвано
[00:10:28:698] [nioEventLoopGroup-0-1/INFO]: Соединение установлено
[00:10:28:725] [nioEventLoopGroup-0-1/INFO]: Decoder HANDSHAKING, packet CHandshake, id 0, size 3
[00:10:28:725] [nioEventLoopGroup-0-1/INFO]: Connect Battle server
[00:10:34:032] [nioEventLoopGroup-0-2/INFO]: Decoder PLAY, packet CPacketAction, id 0, size 15
[00:10:34:033] [nioEventLoopGroup-0-1/INFO]: Encoder BATTLE_SERVER, packet PCreateBattle, id 0, size 16
[00:10:39:444] [nioEventLoopGroup-0-5/INFO]: Decoder BATTLE_SERVER, packet PBattleStatus, id 0, size 7
[00:10:39:447] [nioEventLoopGroup-0-2/INFO]: Encoder PLAY, packet SPacketStartBattle, id 7, size 6
[00:12:51:441] [nioEventLoopGroup-0-5/INFO]: exceptionCaught
java.io.IOException: Удаленный хост принудительно разорвал существующее подключение
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_151]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_151]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_151]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:311) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:853) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:240) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:115) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:514) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:471) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:385) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:351) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
[00:12:51:441] [nioEventLoopGroup-0-5/INFO]: [Test_1, exceptionCaught] lost connection: {}
[00:12:51:441] [nioEventLoopGroup-0-5/INFO]: Соединение разорвано
[00:13:03:784] [nioEventLoopGroup-0-4/INFO]: Соединение установлено
[00:13:03:804] [nioEventLoopGroup-0-4/INFO]: Decoder HANDSHAKING, packet CHandshake, id 0, size 3
[00:13:03:804] [nioEventLoopGroup-0-4/INFO]: Decoder LOGIN, packet CPacketLoginStart, id 0, size 22
[00:13:03:807] [pool-2-thread-1/INFO]: Start initialize player id=1
[00:13:03:808] [pool-2-thread-1/INFO]: End initialize player id=1 name=Test_1
[00:13:03:813] [nioEventLoopGroup-0-4/INFO]: Encoder LOGIN, packet SPacketLoginSuccess, id 1, size 2
[00:13:03:813] [nioEventLoopGroup-0-4/INFO]: Encoder PLAY, packet SPacketPlayerInfo, id 1, size 34
[00:13:03:813] [nioEventLoopGroup-0-4/INFO]: Encoder PLAY, packet SPacketInventory, id 3, size 111
[00:13:03:814] [nioEventLoopGroup-0-4/INFO]: Encoder PLAY, packet SPacketBody, id 4, size 110
[00:13:03:814] [nioEventLoopGroup-0-4/INFO]: Encoder PLAY, packet SPacketSlots, id 9, size 10
[00:13:03:814] [nioEventLoopGroup-0-4/INFO]: Encoder PLAY, packet SPacketLocInfo, id 2, size 200
[00:13:03:814] [nioEventLoopGroup-0-4/INFO]: Encoder PLAY, packet SPacketPlayerLocation, id 8, size 26
[00:13:03:814] [nioEventLoopGroup-0-4/INFO]: Encoder PLAY, packet SPacketPlayerLocation, id 8, size 26
[00:13:05:881] [nioEventLoopGroup-0-4/INFO]: Decoder PLAY, packet CPacketAction, id 0, size 15
[00:13:05:882] [nioEventLoopGroup-0-2/INFO]: Encoder BATTLE_SERVER, packet PCreateBattle, id 0, size 16
[00:13:25:141] [nioEventLoopGroup-0-2/INFO]: Decoder BATTLE_SERVER, packet PBattleStatus, id 0, size 7
[00:13:25:142] [nioEventLoopGroup-0-0/INFO]: Encoder PLAY, packet SPacketStartBattle, id 7, size 6
[00:13:57:952] [nioEventLoopGroup-0-0/INFO]: exceptionCaught
java.io.IOException: Удаленный хост принудительно разорвал существующее подключение
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_151]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_151]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_151]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:311) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:853) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:240) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:115) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:514) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:471) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:385) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:351) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
[00:13:57:953] [nioEventLoopGroup-0-0/INFO]: [Test_1, exceptionCaught] lost connection: {}
[00:13:57:953] [nioEventLoopGroup-0-0/INFO]: Соединение разорвано
[00:15:34:941] [nioEventLoopGroup-0-3/INFO]: Соединение установлено
[00:15:34:952] [nioEventLoopGroup-0-3/INFO]: Decoder HANDSHAKING, packet CHandshake, id 0, size 3
[00:15:34:953] [nioEventLoopGroup-0-3/INFO]: Decoder LOGIN, packet CPacketLoginStart, id 0, size 22
[00:15:34:956] [pool-2-thread-3/INFO]: Start initialize player id=1
[00:15:34:956] [pool-2-thread-3/INFO]: End initialize player id=1 name=Test_1
[00:15:34:958] [nioEventLoopGroup-0-3/INFO]: Encoder LOGIN, packet SPacketLoginSuccess, id 1, size 2
[00:15:34:958] [nioEventLoopGroup-0-3/INFO]: Encoder PLAY, packet SPacketPlayerInfo, id 1, size 34
[00:15:34:958] [nioEventLoopGroup-0-3/INFO]: Encoder PLAY, packet SPacketInventory, id 3, size 111
[00:15:34:959] [nioEventLoopGroup-0-3/INFO]: Encoder PLAY, packet SPacketBody, id 4, size 110
[00:15:34:959] [nioEventLoopGroup-0-3/INFO]: Encoder PLAY, packet SPacketSlots, id 9, size 10
[00:15:34:959] [nioEventLoopGroup-0-3/INFO]: Encoder PLAY, packet SPacketLocInfo, id 2, size 200
[00:15:34:969] [nioEventLoopGroup-0-3/INFO]: Encoder PLAY, packet SPacketPlayerLocation, id 8, size 26
[00:15:34:969] [nioEventLoopGroup-0-3/INFO]: Encoder PLAY, packet SPacketPlayerLocation, id 8, size 26
[00:15:37:001] [nioEventLoopGroup-0-3/INFO]: Decoder PLAY, packet CPacketAction, id 0, size 15
[00:15:37:003] [nioEventLoopGroup-0-5/INFO]: Encoder BATTLE_SERVER, packet PCreateBattle, id 0, size 16
[00:15:37:021] [nioEventLoopGroup-0-5/INFO]: Decoder BATTLE_SERVER, packet PBattleStatus, id 0, size 7
[00:15:37:022] [nioEventLoopGroup-0-3/INFO]: Encoder PLAY, packet SPacketStartBattle, id 7, size 6
[00:18:55:719] [nioEventLoopGroup-0-1/INFO]: exceptionCaught
java.io.IOException: Удаленный хост принудительно разорвал существующее подключение
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_151]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_151]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_151]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:311) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:853) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:240) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:115) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:514) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:471) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:385) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:351) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
[00:18:55:719] [nioEventLoopGroup-0-1/INFO]: [Test_1, exceptionCaught] lost connection: {}
[00:18:55:719] [nioEventLoopGroup-0-1/INFO]: Соединение разорвано
[00:18:58:414] [nioEventLoopGroup-0-6/INFO]: exceptionCaught
java.io.IOException: Удаленный хост принудительно разорвал существующее подключение
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_151]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_151]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_151]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:311) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:853) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:240) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:115) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:514) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:471) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:385) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:351) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
[00:18:58:415] [nioEventLoopGroup-0-6/INFO]: [Battle Server, exceptionCaught] lost connection: {}
[00:18:58:415] [nioEventLoopGroup-0-6/INFO]: Соединение разорвано
[00:19:02:199] [nioEventLoopGroup-0-2/INFO]: Соединение установлено
[00:19:02:210] [nioEventLoopGroup-0-2/INFO]: Decoder HANDSHAKING, packet CHandshake, id 0, size 3
[00:19:02:210] [nioEventLoopGroup-0-2/INFO]: Decoder LOGIN, packet CPacketLoginStart, id 0, size 22
[00:19:02:214] [pool-2-thread-9/INFO]: Start initialize player id=1
[00:19:02:214] [pool-2-thread-9/INFO]: End initialize player id=1 name=Test_1
[00:19:02:218] [nioEventLoopGroup-0-2/INFO]: Encoder LOGIN, packet SPacketLoginSuccess, id 1, size 2
[00:19:02:218] [nioEventLoopGroup-0-2/INFO]: Encoder PLAY, packet SPacketPlayerInfo, id 1, size 34
[00:19:02:219] [nioEventLoopGroup-0-2/INFO]: Encoder PLAY, packet SPacketInventory, id 3, size 111
[00:19:02:219] [nioEventLoopGroup-0-2/INFO]: Encoder PLAY, packet SPacketBody, id 4, size 110
[00:19:02:219] [nioEventLoopGroup-0-2/INFO]: Encoder PLAY, packet SPacketSlots, id 9, size 10
[00:19:02:219] [nioEventLoopGroup-0-2/INFO]: Encoder PLAY, packet SPacketLocInfo, id 2, size 200
[00:19:02:219] [nioEventLoopGroup-0-2/INFO]: Encoder PLAY, packet SPacketPlayerLocation, id 8, size 26
[00:19:02:220] [nioEventLoopGroup-0-2/INFO]: Encoder PLAY, packet SPacketPlayerLocation, id 8, size 26
[00:19:09:719] [nioEventLoopGroup-0-7/INFO]: Соединение установлено
[00:19:09:757] [nioEventLoopGroup-0-7/INFO]: Decoder HANDSHAKING, packet CHandshake, id 0, size 3
[00:19:09:757] [nioEventLoopGroup-0-7/INFO]: Connect Battle server
[00:19:11:683] [nioEventLoopGroup-0-2/INFO]: Decoder PLAY, packet CPacketAction, id 0, size 15
[00:19:11:685] [nioEventLoopGroup-0-7/INFO]: Encoder BATTLE_SERVER, packet PCreateBattle, id 0, size 16
[00:19:11:729] [nioEventLoopGroup-0-9/INFO]: Decoder BATTLE_SERVER, packet PBattleStatus, id 0, size 7
[00:19:11:730] [nioEventLoopGroup-0-2/INFO]: Encoder PLAY, packet SPacketStartBattle, id 7, size 6
[00:19:17:394] [nioEventLoopGroup-0-2/INFO]: Соединение разорвано
[00:20:16:724] [nioEventLoopGroup-0-1/INFO]: exceptionCaught
java.io.IOException: Удаленный хост принудительно разорвал существующее подключение
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_151]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_151]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_151]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:311) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:853) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:240) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:115) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:514) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:471) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:385) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:351) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
[00:20:16:725] [nioEventLoopGroup-0-1/INFO]: [Battle Server, exceptionCaught] lost connection: {}
[00:20:16:725] [nioEventLoopGroup-0-1/INFO]: Соединение разорвано
[00:20:19:481] [nioEventLoopGroup-0-4/INFO]: Соединение установлено
[00:20:19:509] [nioEventLoopGroup-0-4/INFO]: Decoder HANDSHAKING, packet CHandshake, id 0, size 3
[00:20:19:509] [nioEventLoopGroup-0-4/INFO]: Connect Battle server
[00:20:20:588] [nioEventLoopGroup-0-8/INFO]: Соединение установлено
[00:20:20:603] [nioEventLoopGroup-0-8/INFO]: Decoder HANDSHAKING, packet CHandshake, id 0, size 3
[00:20:20:603] [nioEventLoopGroup-0-8/INFO]: Decoder LOGIN, packet CPacketLoginStart, id 0, size 22
[00:20:20:607] [pool-2-thread-1/INFO]: Start initialize player id=1
[00:20:20:608] [pool-2-thread-1/INFO]: End initialize player id=1 name=Test_1
[00:20:20:612] [nioEventLoopGroup-0-8/INFO]: Encoder LOGIN, packet SPacketLoginSuccess, id 1, size 2
[00:20:20:612] [nioEventLoopGroup-0-8/INFO]: Encoder PLAY, packet SPacketPlayerInfo, id 1, size 34
[00:20:20:613] [nioEventLoopGroup-0-8/INFO]: Encoder PLAY, packet SPacketInventory, id 3, size 111
[00:20:20:613] [nioEventLoopGroup-0-8/INFO]: Encoder PLAY, packet SPacketBody, id 4, size 110
[00:20:20:613] [nioEventLoopGroup-0-8/INFO]: Encoder PLAY, packet SPacketSlots, id 9, size 10
[00:20:20:613] [nioEventLoopGroup-0-8/INFO]: Encoder PLAY, packet SPacketLocInfo, id 2, size 200
[00:20:20:614] [nioEventLoopGroup-0-8/INFO]: Encoder PLAY, packet SPacketPlayerLocation, id 8, size 26
[00:20:20:614] [nioEventLoopGroup-0-8/INFO]: Encoder PLAY, packet SPacketPlayerLocation, id 8, size 26
[00:20:22:387] [nioEventLoopGroup-0-8/INFO]: Decoder PLAY, packet CPacketAction, id 0, size 15
[00:20:22:389] [nioEventLoopGroup-0-4/INFO]: Encoder BATTLE_SERVER, packet PCreateBattle, id 0, size 16
[00:20:22:425] [nioEventLoopGroup-0-4/INFO]: Decoder BATTLE_SERVER, packet PBattleStatus, id 0, size 7
[00:20:22:427] [nioEventLoopGroup-0-8/INFO]: Encoder PLAY, packet SPacketStartBattle, id 7, size 6
[00:20:39:343] [nioEventLoopGroup-0-10/INFO]: Соединение разорвано
[00:23:14:433] [nioEventLoopGroup-0-4/INFO]: exceptionCaught
java.io.IOException: Удаленный хост принудительно разорвал существующее подключение
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_151]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_151]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_151]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:311) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:853) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:240) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:115) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:514) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:471) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:385) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:351) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
[00:23:14:434] [nioEventLoopGroup-0-4/INFO]: [Battle Server, exceptionCaught] lost connection: {}
[00:23:14:434] [nioEventLoopGroup-0-4/INFO]: Соединение разорвано
